version: "2"
plugins:
  brakeman:
    channel: brakeman-6-2-1
    enabled: true
  rubocop:
    enabled: true
    channel: rubocop-1-56-3
    config:
      file: .rubocop.yml

exclude_patterns:
  - "vendor/"
  - ".*/"
  - "bin/"
  - "config/"
  - "db/"
  - "lib/"
  - "app/lib/"
  - "proto/"
  - "spec/"
